version: '3'
services:
        myapp2:
                build: .
                ports:
                        - "80:5000"
                networks:
                        - myredpostgres
        dbpostgres:
                image: postgres:9.4
                networks:
                        - myredpostgres
                restart: always
                ports:
                        - "5432:5432"
                environment:
                  POSTGRES_USER: username
                  POSTGRES_PASSWORD: userpass
                volumes:
                        - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
        myredpostgres:
                name: myredpostgres-network      
